blueprint:
  name: Zendure - Charge Progressive Tempo + Solaire + Limitation puissance maison
  description: >
    Charge progressive de la batterie Zendure en Heures Creuses
    selon le niveau de batterie, la couleur Tempo, la prévision solaire
    et la puissance max disponible dans la maison.
  domain: automation

  input:
    tempo_sensor:
      name: Capteur Tempo
      description: Couleur Tempo du lendemain (Bleu / Blanc / Rouge)
      selector:
        entity:
          domain: sensor

    battery_level_sensor:
      name: Niveau de batterie
      description: Niveau de charge de la batterie (%)
      selector:
        entity:
          domain: sensor

    solar_forecast_sensor:
      name: Prévision solaire demain
      description: Énergie solaire prévue demain (kWh)
      selector:
        entity:
          domain: sensor

    zendure_manager:
      name: Zendure Manager
      description: Entité de contrôle du Zendure Manager
      selector:
        entity:
          domain: select

    input_limit:
      name: Limite d'entrée
      description: Entité pour définir la puissance de charge réseau
      selector:
        entity:
          domain: number

    ac_mode:
      name: Mode AC
      description: Entité pour définir le mode AC
      selector:
        entity:
          domain: select

    charge_time:
      name: Heure de déclenchement
      default: "22:00:00"
      selector:
        time:
        
    end_charge_time:
      name: Heure de fin de charge
      description: Heure à laquelle la charge réseau s'arrête
      default: "06:00:00"
      selector:
        time:

    low_battery_threshold:
      name: Seuil batterie faible
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    medium_battery_threshold:
      name: Seuil batterie moyenne
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    solar_medium_threshold:
      name: Seuil solaire moyen
      description: Au-dessus de ce seuil, charge réseau réduite (kWh)
      default: 3.5
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: "kWh"

    solar_good_threshold:
      name: Seuil solaire élevé
      description: Au-dessus de ce seuil, pas de charge réseau (kWh)
      default: 7
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: "kWh"

    high_power_limit:
      name: Puissance charge rapide
      default: 1700
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: "W"

    medium_power_limit:
      name: Puissance charge normale
      default: 1200
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: "W"

    low_power_limit:
      name: Puissance charge douce
      default: 600
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: "W"

    puissance_max_kva:
      name: Puissance contrat (kVA)
      description: Puissance maximale disponible, convertie automatiquement en W
      default: 9
      selector:
        number:
          min: 3
          max: 36
          step: 1
          unit_of_measurement: "kVA"

    home_power_sensor:
      name: Puissance instantanée maison (W)
      description: Consommation actuelle du foyer
      selector:
        entity:
          domain: sensor

trigger:
  - platform: time
    at: !input charge_time
    id: start_charge

  - platform: time
    at: !input end_charge_time
    id: end_charge
  
  - platform: state
    entity_id: !input home_power_sensor

condition:
  - condition: and
    conditions:
      - condition: time
        after: !input charge_time
      - condition: time
        before: !input end_charge_time
    
  - condition: or
    conditions:
      - condition: state
        entity_id: !input tempo_sensor
        state: "Blanc"
      - condition: state
        entity_id: !input tempo_sensor
        state: "Rouge"

action:
  # Sécurité : on coupe avant décision
  - action: select.select_option
    target:
      entity_id: !input zendure_manager
    data:
      option: "off"

  # Calcul marge puissance disponible
  - variables:
      puissance_max_kva: !input puissance_max_kva
      home_power_sensor: !input home_power_sensor
      puissance_max_w: "{{ (puissance_max_kva | int(6)) * 1000 }}"
      conso_maison: "{{ states(home_power_sensor) | float(0) }}"
      marge_dispo: "{{ puissance_max_w - conso_maison }}"

  - choose:
      # ⛔ Heure de fin → arrêt charge réseau
      - conditions:
          - condition: trigger
            id: end_charge
        sequence:
          - action: select.select_option
            target:
              entity_id: !input ac_mode
            data:
              option: "output"

          - action: select.select_option
            target:
              entity_id: !input zendure_manager
            data:
              option: "off"

          - stop: "Fin de période HC – passage en mode output"

      # ☀️ Soleil élevé → pas de charge réseau
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            above: !input solar_good_threshold
        sequence:
          - action: select.select_option
            target:
              entity_id: !input zendure_manager
            data:
              option: "off"

      # 🌤️ Soleil moyen → charge douce
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            above: !input solar_medium_threshold
            below: !input solar_good_threshold
        sequence:
          - variables:
              puissance_voulue: !input low_power_limit
              puissance_effective: "{{ [puissance_voulue, marge_dispo] | min }}"
          - action: number.set_value
            data:
              value: "{{ puissance_effective }}"
            target:
              entity_id: !input input_limit
          - action: select.select_option
            data:
              option: "input"
            target:
              entity_id: !input ac_mode

      # 🌧️ Peu de soleil → charge selon batterie
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            below: !input solar_medium_threshold
        sequence:
          - choose:

              # Batterie faible → puissance haute
              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    below: !input low_battery_threshold
                sequence:
                  - variables:
                      puissance_voulue: !input high_power_limit
                      puissance_effective: "{{ [puissance_voulue, marge_dispo] | min }}"
                  - action: number.set_value
                    data:
                      value: "{{ puissance_effective }}"
                    target:
                      entity_id: !input input_limit

              # Batterie moyenne → puissance médium
              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    below: !input medium_battery_threshold
                sequence:
                  - variables:
                      puissance_voulue: !input medium_power_limit
                      puissance_effective: "{{ [puissance_voulue, marge_dispo] | min }}"
                  - action: number.set_value
                    data:
                      value: "{{ puissance_effective }}"
                    target:
                      entity_id: !input input_limit

              # Batterie bonne → charge douce
              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    above: !input medium_battery_threshold
                sequence:
                  - variables:
                      puissance_voulue: !input low_power_limit
                      puissance_effective: "{{ [puissance_voulue, marge_dispo] | min }}"
                  - action: number.set_value
                    data:
                      value: "{{ puissance_effective }}"
                    target:
                      entity_id: !input input_limit

          - action: select.select_option
            data:
              option: "input"
            target:
              entity_id: !input ac_mode

mode: single
