blueprint:
  name: Zendure – Charge Progressive Tempo + Solaire
  description: >
    Charge intelligente de la batterie Zendure selon la couleur Tempo,
    le niveau de batterie et la prévision de production solaire (Forecast Solar).
  domain: automation

  input:
    tempo_sensor:
      name: Capteur Tempo (demain)
      selector:
        entity:
          domain: sensor

    solar_forecast_sensor:
      name: Prévision solaire (kWh demain)
      selector:
        entity:
          domain: sensor

    battery_level_sensor:
      name: Niveau de batterie (%)
      selector:
        entity:
          domain: sensor

    zendure_manager:
      name: Zendure Manager
      selector:
        entity:
          domain: select

    input_limit:
      name: Limite de puissance AC (W)
      selector:
        entity:
          domain: number

    ac_mode:
      name: Mode AC Zendure
      selector:
        entity:
          domain: select

    charge_time:
      name: Heure de déclenchement
      default: "22:00:00"
      selector:
        time:

    # --- Seuils solaires ---
    solar_high_threshold:
      name: Seuil solaire haut (kWh)
      default: 2.0
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    solar_medium_threshold:
      name: Seuil solaire moyen (kWh)
      default: 1.0
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    # --- Seuils batterie ---
    low_battery_threshold:
      name: Batterie faible (%)
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    medium_battery_threshold:
      name: Batterie moyenne (%)
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"

    # --- Puissances ---
    high_power_limit:
      name: Puissance charge forte (W)
      default: 1700
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: W

    medium_power_limit:
      name: Puissance charge normale (W)
      default: 1200
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: W

    low_power_limit:
      name: Puissance charge douce (W)
      default: 600
      selector:
        number:
          min: 0
          max: 2400
          unit_of_measurement: W

trigger:
  - platform: time
    at: !input charge_time

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: !input tempo_sensor
        state: "Blanc"
      - condition: state
        entity_id: !input tempo_sensor
        state: "Rouge"

action:
  # Sécurité : on coupe avant de décider
  - action: select.select_option
    target:
      entity_id: !input zendure_manager
    data:
      option: "off"

  - choose:
      # ☀️ Soleil élevé → pas de charge réseau
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            above: !input solar_high_threshold
        sequence:
          - action: select.select_option
            target:
              entity_id: !input zendure_manager
            data:
              option: "off"

      # 🌤️ Soleil moyen → charge douce
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            above: !input solar_medium_threshold
            below: !input solar_high_threshold
        sequence:
          - action: number.set_value
            target:
              entity_id: !input input_limit
            data:
              value: !input low_power_limit
          - action: select.select_option
            target:
              entity_id: !input ac_mode
            data:
              option: "input"

      # 🌧️ Peu de soleil → charge selon niveau batterie
      - conditions:
          - condition: numeric_state
            entity_id: !input solar_forecast_sensor
            below: !input solar_medium_threshold
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    below: !input low_battery_threshold
                sequence:
                  - action: number.set_value
                    target:
                      entity_id: !input input_limit
                    data:
                      value: !input high_power_limit

              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    below: !input medium_battery_threshold
                sequence:
                  - action: number.set_value
                    target:
                      entity_id: !input input_limit
                    data:
                      value: !input medium_power_limit

              - conditions:
                  - condition: numeric_state
                    entity_id: !input battery_level_sensor
                    above: !input medium_battery_threshold
                sequence:
                  - action: number.set_value
                    target:
                      entity_id: !input input_limit
                    data:
                      value: !input low_power_limit

          - action: select.select_option
            target:
              entity_id: !input ac_mode
            data:
              option: "input"

mode: single
